language: python
python:
  - "3.5"
env:
    - TOX_ENV=py26-django13
    - TOX_ENV=py26-django14
    - TOX_ENV=py26-django15
    - TOX_ENV=py26-django16
    - TOX_ENV=py27-django13
    - TOX_ENV=py27-django14
    - TOX_ENV=py27-django15
    - TOX_ENV=py27-django16
    - TOX_ENV=py27-django17
    - TOX_ENV=py27-django18
    - TOX_ENV=py27-django19
    - TOX_ENV=py27-django110
    - TOX_ENV=py27-django111
    - TOX_ENV=py27-djangomaster
    - TOX_ENV=py34-django16
    - TOX_ENV=py34-django17
    - TOX_ENV=py34-django18
    - TOX_ENV=py34-django19
    - TOX_ENV=py34-django110
    - TOX_ENV=py34-django111
    - TOX_ENV=py34-djangomaster
    - TOX_ENV=py35-django18
    - TOX_ENV=py35-django19
    - TOX_ENV=py35-django110
    - TOX_ENV=py35-django111
    - TOX_ENV=py35-djangomaster

matrix:
    allow_failures:
        - env: TOX_ENV=py27-djangomaster
        - env: TOX_ENV=py34-djangomaster
        - env: TOX_ENV=py35-djangomaster

install:
    - pip install tox

script: tox -e $TOX_ENV
